language: php

php:
  - 7.2

before_script:
  - cp .env.travis .env
  - mysql -u root -e 'create database pizzaApp;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
